apiVersion: v1
kind: Service
metadata:
  name: okk5
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okk5"
    port: 8080
  selector:
    app: okk5
